helloworld/helloworld/urls.py
# from django.contrib import admin
# from django.urls import path

# urlpatterns = [
#     path('admin/', admin.site.urls),
# ]

from django.urls.conf import include 
from django.contrib import admin 
from django.urls import path  

urlpatterns = [
    # URL padrão 
    path('',include('website.urls', namespace='website')),

    # Interface administrativa 
    path('admin', admin.site.urls),
]

helloworld/website/urls.py
#

from . import views
from django.urls import path 
from django.views.generic import TemplateView 
from website.views import IndexTemplateView
from website.views import FuncionarioListView
from website.views import FuncionarioDeleteView
from website.views import FuncionarioCreateView
from website.views import FuncionarioUpdateView



app_name = 'website' 

# urlpatterns = [
#     # path('funcionarios/<int:ano>/', views.funcionarios_por_ano),
# ]

urlpatterns = [
    # path('', TemplateView.as_view(template_name="index.html")),
    path('', IndexTemplateView.as_view(), name="index"),

    path('funcionario/cadastrar', FuncionarioCreateView.as_view(),name="cadastra_funcionario"),
    
    path('funcionarios/', FuncionarioListView.as_view(),name="lista_funcionarios"),

    # {id} para busca
    path('funcionario/<pk>', FuncionarioUpdateView.as_view(),name="atualiza_funcionario"),
    # {slug} para busca 
    # path('funcionario/<slug>', FuncionarioUpdateView.as_view()),
    path('funcionario/excluir/<pk>', FuncionarioDeleteView.as_view(),name="deleta_funcionario"),
    
] 

helloworld/helloworld/models.py
from django.db import models

# Create your models here.

class Funcionario(models.Model):
    nome = models.CharField(
        max_length=255,
        null=False,
        blank=False
    )

    sobrenome = models.CharField(
        max_length=255,
        null=False,
        blank=False
    )

    cpf = models.CharField(
        max_length=14,
        null=False,
        blank=False
    )

    tempo_de_servico = models.IntegerField(
        default=0,
        null=False,
        blank=False
    )

    remuneracao = models.DecimalField(
        max_digits=8,
        decimal_places=2,
        null=False,
        blank=False
    )

    objetos = models.Manager()

helloworld/website/forms.py
from helloworld.models import Funcionario

from django import forms 

class InsereFuncionarioForm(forms.ModelForm): 

    # chefe = forms.BooleanField(
    # label='Chefe?',
    # required=True,
    # )

    # biografia = forms.CharField(
    #     label = 'Biografia',
    #     required = False,
    #     widget = forms.TextArea
    # )

    class Meta: 
        model = Funcionario 

        fields = [
        'nome',
        'sobrenome',
        'cpf',
        'tempo_de_servico',
        'remuneracao',
        'tempo_de_servico'
        ]

        exclude = [
            
        ]

helloworld/website/views.py
from django.urls import reverse_lazy

from django.shortcuts import render
from helloworld.models import Funcionario  

from django.views.generic import TemplateView
from django.views.generic import ListView 
from django.views.generic import UpdateView 
from django.views.generic import CreateView
from django.views.generic import DeleteView

from website.forms import InsereFuncionarioForm


# Create your views here.

class IndexTemplateView(TemplateView):
    template_name = "website/index.html" 

class FuncionarioListView(ListView):
    template_name = "website/lista.html"
    model = Funcionario
    context_object_name = "funcionarios" 

# class FuncionarioUpdateView(UpdateView):
#     template_name = "atualiza.html" 
#     model = Funcionario
#     fields = [
#         'nome',
#         'sobrenome',
#         'cpf',
#         'tempo_de_servico',
#         'remuneracao'
#     ]

class FuncionarioUpdateView(UpdateView):
    template_name="website/atualiza.html"
    model = Funcionario
    fields = '__all__'
    context_object_name = 'funcionario'
    success_url = reverse_lazy("website:lista_funcionarios")


    def get_object(self,queryset=None):
        funcionario = None

        pk = self.kwargs.get(self.pk_url_kwarg)
        slug = self.kwargs.get(self.slug_url_kwarg) 

        if pk is not None:
            # Busca pelo ID
            funcionario = Funcionario.objetos.filter(pk=pk).first()

        elif slug is not None:
            # pega o slug do Model
            campo_slug = self.get_slug_field() 

            # Busca pelo slug 
            funcionario = Funcionario.objetos.filter(**{campo_slug:slug}).first()

        return funcionario

class FuncionarioDeleteView(DeleteView):
    template_name = "website/exclui.html" 
    model = Funcionario 
    context_object_name = 'funcionario' 
    success_url = reverse_lazy("website:lista_funcionarios")

class FuncionarioCreateView(CreateView):
    template_name="website/cria.html"
    model = Funcionario
    form_class = InsereFuncionarioForm
    success_url = reverse_lazy("website:lista_funcionarios")

helloworld/website/templates/website/atualiza.html
<!DOCTYPE html>
{% load crispy_forms_tags %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
    <title>Title</title>
</head>
<body>
    <header class="container">
        <h1>Página de Atualização de Funcionário</h1>
    
        <ul>
            <li><a href="{% url 'website:index' %}">Página Inicial</a></li>
            <li><a href="{% url 'website:cadastra_funcionario' %}">Cadastrar Funcionário</a></li>
            <li><a href="{% url 'website:lista_funcionarios' %}">Lista de Funcionários</a></li>
        </ul>
    </header>

    <main class="container">
        <form method="post">
            <!-- É necessário colocar o código abaixo em toda página que                   -->
            <!-- contenha um formulário para evitar o ataque de Cross Site Request Forgery -->
            {% csrf_token %}
    
            {{ form|crispy}}
    
            <button class="btn btn-primary">Enviar</button>
        </form>
    </main>
</body>
</html>

helloworld/website/templates/website/cria.html
<!DOCTYPE html>
{% load crispy_forms_tags %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
    <title>Title</title>
</head>
<body>

    <header class="container">
        <h1>Página de Inserção de Funcionário</h1>
    
        <ul>
            <li><a href="{% url 'website:index' %}">Página Inicial</a></li>
            <li><a href="{% url 'website:cadastra_funcionario' %}">Cadastrar Funcionário</a></li>
            <li><a href="{% url 'website:lista_funcionarios' %}">Lista de Funcionários</a></li>
        </ul>
    </header>

    <main class="container">
        <form method="post">
            <!-- É necessário colocar o código abaixo em toda página que                   -->
            <!-- contenha um formulário para evitar o ataque de Cross Site Request Forgery -->
            {% csrf_token %}
    
            {{ form|crispy }}
    
            <button class="btn btn-primary">Enviar</button>
        </form>
    </main>
</body>
</html>

helloworld/website/templates/website/exclui.html
<!DOCTYPE html>
{% load crispy_forms_tags %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
    <title>Title</title>
</head>
<body>
    <header class="container">
        <h1>Página de Atualização de Funcionário</h1>
    
        <ul>
            <li><a href="{% url 'website:index' %}">Página Inicial</a></li>
            <li><a href="{% url 'website:cadastra_funcionario' %}">Cadastrar Funcionário</a></li>
            <li><a href="{% url 'website:lista_funcionarios' %}">Lista de Funcionários</a></li>
        </ul>
    </header>

    <form method="post" style="border: 1px solid #AAA; margin: 64px auto; padding: 32px; width: 50%;">
        <!-- É necessário colocar o código abaixo em toda página que                   -->
        <!-- contenha um formulário para evitar o ataque de Cross Site Request Forgery -->
        {% csrf_token %}

        Você tem certeza que quer excluir o funcionário <b>{{ funcionario.nome }}</b>? <br><br>

        <button type="button">
            <a class="btn btn-primary" href="{% url 'website:lista_funcionarios' %}">Cancelar</a>
        </button>
        <button class="btn btn-danger">Excluir</button>
    </form>


    <div class="modal" tabindex="-1" role="dialog">
        <div class="modal-dialog" role="document">
          <div class="modal-content">
            <div class="modal-header">
              <h5 class="modal-title">Modal title</h5>
              <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                <span aria-hidden="true">&times;</span>
              </button>
            </div>
            <div class="modal-body">
                {% csrf_token %}

               <p>Você tem certeza que quer excluir o funcionário <b>{{ funcionario.nome }}</b>?</p>
            </div>
            <div class="modal-footer">
              <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
              <button type="button" class="btn btn-primary">Save changes</button>
            </div>
          </div>
        </div>
      </div>

</body>
</html>

helloworld/website/templates/website/index.html
<!DOCTYPE html>
{% load crispy_forms_tags %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
    <title>Title</title>
</head>
<body>
    <header class="container">
        <h1>Página Inicial</h1>
    
        <ul>
            <li><a href="{% url 'website:index' %}">Página Inicial</a></li>
            <li><a href="{% url 'website:cadastra_funcionario' %}">Cadastrar Funcionário</a></li>
            <li><a href="{% url 'website:lista_funcionarios' %}">Lista de Funcionários</a></li>
        </ul>
    </header>
</body>
</html>

helloworld/website/templates/website/lista.html
<!DOCTYPE html>
{% load crispy_forms_tags %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <!-- <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous"> -->

    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
    <title>Title</title>
</head>
<body>

    <header class="container">
        <h1>Lista de Funcionários</h1>
    
        <ul>
            <li><a href="{% url 'website:index' %}">Página Inicial</a></li>
            <li><a href="{% url 'website:cadastra_funcionario' %}">Cadastrar Funcionário</a></li>
            <li><a href="{% url 'website:lista_funcionarios' %}">Lista de Funcionários</a></li>
        </ul>
    </header>

    <main class="container">
        <div class="d-flex">
            <table class="w-75 text-center table table-bordered">
                <thead class="bg-light">
                    <tr>
                        <td><b>Nome</b></td>
                        <td><b>CPF</b></td>
                        <td><b>Remuneração</b></td>
                        <td><b>Tempo de Serviço</b></td>
                        <td colspan="2"><b>Ações</b></td>
                    </tr>
                </thead>
    
                <tbody>
                    {% for funcionario in funcionarios %}
                        <tr>
                            <td>{{ funcionario.nome }} {{ funcionario.sobrenome }}</td>
                            <td>{{ funcionario.cpf }}</td>
                            <td>{{ funcionario.remuneracao }}</td>
                            <td>{{ funcionario.tempo_de_servico }}</td>
                            <td><a href="{% url 'website:atualiza_funcionario' pk=funcionario.id %}">Atualizar</a></td>
                            <td><a href="{% url 'website:deleta_funcionario' pk=funcionario.id %}">Excluir</a></td>
                        </tr>
                    {% endfor %}
                </tbody>
                
            </table>
        </div>
    </main>

</body>
</html>